# 服务端口
server:
  port: 8004
  # 服务名
spring:
  application:
      name: service-cms
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #注册到Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.81.128:8848
  redis:
    host: 192.168.81.128
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

  #配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/atguigu/educms/mapper/xml/*.xml
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl