server:
  port: 10000

spring:
  application:
    name: canal-client
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_canal?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456