server:
  port: 8007

spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        #nacos服务注册地址
        server-addr: 192.168.81.128:8848

feign:
  hystrix:
    #feign开启hystrix
    enabled: true


mybatis-plus:
  type-aliases-package: com.atguigu.eduorder.entity
  mapper-locations: classpath:com/atguigu/eduorder/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
